### ISSUE TITLE
Dealing with different action types

### ISSUE THREAD

**Issue by Jailander** [LCAS/topological_navigation#36]
In the original version of topological navigation all actions had to have move base type, this should not be the case anymore, and the action type should be explicitly defined for each action. 

The proposed new map (#35 ) allows for the definition of the action type and properties of the destination node can be passed through to the action via the goal field definition. As seen on the new edge definition:  

```yaml
    edges:                        # List of edges departing from the node
    - action: move_action                # Action Name
      edge_id: WayPoint001_WayPoint002
      node: WayPoint002
      config: []
      recovery_behaviours_config: ''
      action_type: 'move_action_msgs/MoveActionGoal'      # Goal type for the Action
      goal:
        target_pose:
          header:
            frame_id: $node.parent_frame
          pose: $node.pose
```

Monitored navigation to be removed.
