### ISSUE TITLE
Merging reconf_at_edges_server into Navigation

### ISSUE THREAD

**Issue by Jailander** [LCAS/topological_navigation#37]
The action reconfiguration at edges was a late addition to our navigation pipeline and it was a bit messy, mainly because its a separate service configured by a different file which adds a lot of complexity to the system, additional points of problems and unnecessary delays. 

The way to overcome this, is to fully integrate the edge re-configuring into the navigation server (#33 ). The new map format (#35 ) already provides for this in the edge definition where the *`config`* field can be used to define parameters that can be reconfigured using the `rqt_reconfigure` interface.

```yaml
edges:                              # List of edges departing from the node
  - action: move_action               # Action Name
    node: WayPoint002
    config: &move_action_config_1             # Action Configuration
      inflation_radius: 0.0                   # Action Parameters
      top_vel: 0.55
      recovery_behaviours_config: ''
    action_type: 'move_action_msgs/MoveActionGoal'      # Goal type for the Action
    goal:
      target_pose: $node.pose
```

**Comment by Jailander** [comment]
@adambinch do you think of the *`config`* field? will we need more parameters? (I was thinking name of reconf server)

**Comment by adambinch** [comment]
Edge config is now:

```yaml
    edges:                        # List of edges departing from the node
    - action: move_action                # Action Name
      edge_id: WayPoint001_WayPoint002
      node: WayPoint002
      config: &move_action_config_1             # Edge Reconfigure
      - namespace: param1_namespace                   # Parameter
        name: param1_name
        value: param1_value
      - namespace: param2_namespace                   # Parameter
        name: param2_name
        value: param2_value
```
